language: python
python:
    # in order of most-valuable tests first
    - "3.5"
    - "2.6"
    - "2.7"
    - "3.4"

script: make

# sudo:false gives us the new, faster cluster and enables caches for public repos
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false
