#!/bin/bash
set -ex

# clean up anything left behind from before:
rm -f .coverage .coverage.*

# See: http://nedbatchelder.com/code/coverage/subprocess.html
COVERAGE_PROCESS_START=.coveragerc py.test -n 100 "$@" ./tests

coverage combine
coverage report --fail-under 100
